[package]
name = "textfile_stats"
version = "0.1.0"
edition = "2021"
authors = ["Harry Obaseki <harry.obaseki@homeflow.co.uk>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.3" }
content_inspector = { version = "0.2.3" }
